<?php 
// Generated by Subsite::writeHostMap() on 02/Oct/14
$subsiteHostmap = array (
  'pir.grandpacifichealth.local' => 'pir.grandpacifichealth.local',
  'scfh.grandpacifichealth.local' => 'scfh.grandpacifichealth.local',
);