<?php 
// Generated by Subsite::writeHostMap() on 25/Nov/14
$subsiteHostmap = array (
  'ispir.org.au.tmp.anchor.net.au' => 'www.ispir.org.au',
  'ispir.org.au' => 'www.ispir.org.au',
  'ispir.gph.local' => 'www.ispir.org.au',
  'pir.grandpacifichealth.local' => 'www.ispir.org.au',
  'scfh.org.au.tmp.anchor.net.au' => 'scfh.org.au',
  'scfh.org.au' => 'scfh.org.au',
);