<?php 
// Generated by Subsite::writeHostMap() on 19/Aug/14
$subsiteHostmap = array (
  'peopleserveprs.com' => 'prs.peopleserveinc.local',
  'prs.peopleserveinc.local' => 'prs.peopleserveinc.local',
  'techwomenboston.com' => 'twb.peopleserveinc.local',
  'twb.peopleserveinc.local' => 'twb.peopleserveinc.local',
);